post http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlkIjoiNjVlZjA3MTI4OTdmYjY3ODBiZDA5MDczIiwiaWF0IjoxNzEwMjQ0NjAzLCJleHAiOjE3MTAyNDgyMDN9.ZurlLM6dEikziqgLtMyl8NGLZJsOIOrZCXXHgVsqgqE


{
    "title": "Token testing",
    "author": "Author of token testing",
    "url": "The url"
}